version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: local
    container_name: sabpaisa-backend-local
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - sabpaisa-network

  # Optional: If you want to see H2 console logs
  h2-console:
    image: alpine:latest
    container_name: h2-console-info
    command: sh -c "echo 'H2 Console is available at http://localhost:8082/h2-console' && echo 'JDBC URL: jdbc:h2:mem:sabpaisa_tokenization_local' && echo 'Username: sa' && echo 'Password: (leave blank)' && tail -f /dev/null"
    networks:
      - sabpaisa-network

networks:
  sabpaisa-network:
    driver: bridge