version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sabpaisa-postgres
    environment:
      POSTGRES_DB: sabpaisa_tokenization
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sabpaisa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sabpaisa-redis
    ports:
      - "6379:6379"
    networks:
      - sabpaisa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sabpaisa-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sabpaisa.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    networks:
      - sabpaisa-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  sabpaisa-network:
    driver: bridge