# Production Environment Configuration
# All sensitive values should be provided through environment variables or AWS Secrets Manager

spring:
  config:
    activate:
      on-profile: prod
      
  datasource:
    # Production database configuration from environment variables
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://prod-db-endpoint:5432/sabpaisa_tokenization}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Use validate for production, update for first deployment
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false
  
    
  redis:
    host: ${REDIS_HOST:prod-redis-endpoint}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 5s
    lettuce:
      pool:
        max-active: 8
        max-idle: 5
        min-idle: 1
    
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutes
      cache-null-values: false
    
  security:
    jwt:
      # Production JWT secret from environment variable or AWS Secrets Manager
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:3600000} # 1 hour default, configurable
      
  mail:
    host: ${MAIL_HOST:email-smtp.us-east-1.amazonaws.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}
  error:
    include-message: always # Show messages in staging for debugging
    include-binding-errors: always
    include-stacktrace: on-param # Show stack trace with ?trace=true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  forward-headers-strategy: native # For AWS ALB

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true # Enabled for production
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
    try-it-out-enabled: true
    
logging:
  level:
    root: INFO
    com.sabpaisa.tokenization: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/sabpaisa/tokenization-service-prod.log
    max-size: 10MB
    max-history: 15

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Application specific properties
app:
  # Encryption configuration
  encryption:
    enabled: true
    master-key: ${ENCRYPTION_MASTER_KEY:dGVzdGVuY3J5cHRpb25rZXlmb3Jwcm9kdWN0aW9uMTIzNDU2Nzg5MGFiY2RlZg==}
    algorithm: AES/GCM/NoPadding
    exclude-paths: /actuator/**,/v3/api-docs/**,/swagger-ui/**
  
  # Notification configuration
  notification:
    enabled: true
    from-email: ${NOTIFICATION_FROM_EMAIL:noreply@sabpaisa.com}
    async: true
    retry-attempts: 2
  
  # SMS configuration
  sms:
    provider: ${SMS_PROVIDER:mock}
    api-key: ${SMS_API_KEY:dummy-sms-key-prod}
    sender-id: ${SMS_SENDER_ID:SBPAIS}
    region: ${AWS_REGION:ap-south-1}
  
  # Monetization configuration
  monetization:
    enabled: true
    free-tier-tokens: ${FREE_TIER_TOKENS:5000}
    rate-limit-per-minute: 200
    rate-limit-per-hour: 5000
  
  # Scheduled tasks
  scheduling:
    enabled: true
    thread-pool-size: 3
    
  # Security configuration
  security:
    rate-limiting:
      enabled: true
      requests-per-minute: 120
      requests-per-hour: 2000
    ip-whitelist:
      enabled: false
    
  # AWS configuration
  aws:
    region: ${AWS_REGION:ap-south-1}
    s3:
      bucket: ${S3_BUCKET:sabpaisa-tokenization-prod}
    kms:
      key-id: ${KMS_KEY_ID:alias/sabpaisa-tokenization-key}
    
  # CORS configuration for production
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://tokenization.sabpaisa.com}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Feature flags for production
feature:
  biometric:
    enabled: ${FEATURE_BIOMETRIC_ENABLED:true}
  enterprise:
    enabled: ${FEATURE_ENTERPRISE_ENABLED:true}
  bulk-tokenization:
    enabled: ${FEATURE_BULK_TOKENIZATION_ENABLED:true}
    max-batch-size: 1000
  fraud-detection:
    enabled: ${FEATURE_FRAUD_DETECTION_ENABLED:true}
    threshold: 0.8
  quantum-encryption:
    enabled: ${FEATURE_QUANTUM_ENCRYPTION_ENABLED:false}
  multi-cloud:
    enabled: ${FEATURE_MULTI_CLOUD_ENABLED:true}
    
# Resilience configuration
resilience4j:
  circuitbreaker:
    instances:
      payment-service:
        sliding-window-size: 50
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 60
        event-consumer-buffer-size: 10
  retry:
    instances:
      payment-service:
        max-attempts: 2
        wait-duration: 500ms
  ratelimiter:
    instances:
      api:
        limit-for-period: 2000
        limit-refresh-period: 1m
        timeout-duration: 0s
