spring:
  application:
    name: sabpaisa-tokenization-backend
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always