spring:
  application:
    name: tokenization-service
    
  datasource:
    url: jdbc:postgresql://postgres:5432/sabpaisa_tokenization
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    
  redis:
    host: redis
    port: 6379
    timeout: 10s
    
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    
logging:
  level:
    com.sabpaisa.tokenization: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
    
# Application specific configurations
app:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  encryption:
    master-key: ${ENCRYPTION_MASTER_KEY:dGhpc2lzYXRlc3RrZXlmb3JkZXZlbG9wbWVudHB1cnBvc2VzMTIzNDU2Nzg=}
  monetization:
    enabled: true
    free-tier-tokens: 1000
  notification:
    from-email: noreply@sabpaisa.com
    enabled: true
  sms:
    provider: mock
    api-key: test-key
    sender-id: SBPAIS