spring:
  application:
    name: tokenization-service
    
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
    
  h2:
    console:
      enabled: true
      path: /h2-console
    
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /tokenization-backend
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    
logging:
  level:
    com.sabpaisa.tokenization: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    root: INFO

# Application specific properties
app:
  encryption:
    enabled: true
    exclude-paths: /health,/actuator/**,/swagger-ui/**,/v3/api-docs/**
  notification:
    enabled: true
    from-email: noreply@sabpaisa.com
  sms:
    provider: mock
    sender-id: SBPAIS
  monetization:
    enabled: true
    free-tier-tokens: 1000
  scheduling:
    enabled: true